#!/bin/bash

echo "========================================="
echo "   QUICK SUPABASE SETUP FOR PUNCTUAL.AI"
echo "========================================="
echo ""
echo "Choose the easiest option for you:"
echo ""
echo "OPTION 1: I'll create a project for you (EASIEST)"
echo "------------------------------------------------"
echo "Just go to: https://database.new"
echo "1. Sign in with GitHub/Google"
echo "2. Click 'New Project'" 
echo "3. Name it 'punctual-ai'"
echo "4. Choose any region"
echo "5. Copy the database password it shows you"
echo "6. Click 'Create new project'"
echo "7. Wait 2 minutes for setup"
echo "8. Go to Settings > API"
echo "9. You'll see 3 values we need"
echo ""
echo "Then paste them here when ready..."
